# Use an official MongoDB image as a base image
FROM mongo:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin_password
ENV MONGO_INITDB_DATABASE=mydatabase

# Copy MongoDB initialization script to the container
COPY init-mongo.js /docker-entrypoint-initdb.d/

# Expose MongoDB default port
EXPOSE 27017

# Optionally, you can specify a volume to persist data
# VOLUME ["/data/db"]

# CMD instruction is not required as it's already specified in the base image
# CMD ["mongod"]
